- id: doi:10.1038/s41596-023-00891-y
  title: Assembly of complete mouse embryo models from embryonic and induced stem
    cell types in vitro
  authors:
  - Kasey Y. C. Lau
  - Gianluca Amadei
  - Magdalena Zernicka-Goetz
  publisher: Nature Protocols
  date: '2023-10-11'
  link: https://doi.org/gtnv99
  orcid: 0000-0001-5405-968X
  plugin: sources.py
  file: sources.yaml
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41596-023-00891-y/MediaObjects/41596_2023_891_Fig1_HTML.png
  
- id: doi:10.1007/7651_2023_493
  title: Generation of Stem Cell-Based Mouse Embryo-Like Structures
  authors:
  - Charlotte E. Handford
  - Pallavi Panda
  - Ikbal B. Mohammad Choudhury
  - Gianluca Amadei
  - Magdalena Zernicka-Goetz
  publisher: Embryo Models In Vitro
  date: '2023-01-01'
  link: https://doi.org/gtnwbb
  orcid: 0000-0001-5405-968X
  plugin: orcid.py
  file: orcid.yaml
- id: doi:10.1098/rsob.220325
  title: Behind the developing brains and beating hearts of stem cell-derived embryo
    models
  authors:
  - Gianluca Amadei
  - David M. Glover
  publisher: Open Biology
  date: '2023-01-01'
  link: https://doi.org/gtnwbc
  orcid: 0000-0001-5405-968X
  plugin: orcid.py
  file: orcid.yaml
- id: doi:10.1038/s41467-023-40322-w
  title: 'spinDrop: a droplet microfluidic platform to maximise single-cell sequencing
    information content'
  authors:
  - Joachim De Jonghe
  - Tomasz S. Kaminski
  - David B. Morse
  - Marcin Tabaka
  - Anna L. Ellermann
  - Timo N. Kohler
  - Gianluca Amadei
  - Charlotte E. Handford
  - Gregory M. Findlay
  - Magdalena Zernicka-Goetz
  - Sarah A. Teichmann
  - Florian Hollfelder
  publisher: Nature Communications
  date: '2023-08-08'
  link: https://doi.org/gtnwbf
  orcid: 0000-0001-5405-968X
  plugin: orcid.py
  file: orcid.yaml
- id: doi:10.1016/j.stem.2022.08.013
  title: Mouse embryo model derived exclusively from embryonic stem cells undergoes
    neurulation and heart development
  authors:
  - Kasey Y.C. Lau
  - Hernan Rubinstein
  - Carlos W. Gantner
  - Ron Hadas
  - Gianluca Amadei
  - Yonatan Stelzer
  - Magdalena Zernicka-Goetz
  publisher: Cell Stem Cell
  date: '2022-10-01'
  link: https://doi.org/gqr8qj
  orcid: 0000-0001-5405-968X
  plugin: orcid.py
  file: orcid.yaml
- id: doi:10.1038/s41586-022-05246-3
  title: "Embryo\_model completes gastrulation to neurulation and organogenesis"
  authors:
  - Gianluca Amadei
  - Charlotte E. Handford
  - Chengxiang Qiu
  - Joachim De Jonghe
  - Hannah Greenfeld
  - Martin Tran
  - Beth K. Martin
  - Dong-Yuan Chen
  - Alejandro Aguilera-Castrejon
  - Jacob H. Hanna
  - Michael B. Elowitz
  - Florian Hollfelder
  - Jay Shendure
  - David M. Glover
  - Magdalena Zernicka-Goetz
  publisher: Nature
  date: '2022-08-25'
  link: https://doi.org/h9cx
  orcid: 0000-0001-5405-968X
  plugin: orcid.py
  file: orcid.yaml
- id: doi:10.1101/2022.08.01.502371
  title: Mouse-embryo model derived exclusively from embryonic stem cells undergo
    neurulation and heart development
  authors:
  - Kasey Y.C. Lau
  - Hernan Rubinstein
  - Carlos W. Gantner
  - Gianluca Amadei
  - Yonatan Stelzer
  - Magdalena Zernicka-Goetz
  publisher: Cold Spring Harbor Laboratory
  date: '2022-08-02'
  link: https://doi.org/gsz9p8
  orcid: 0000-0001-5405-968X
  plugin: orcid.py
  file: orcid.yaml
- id: doi:10.1101/2022.08.01.502375
  title: Stem cell-derived mouse embryos develop within an extra-embryonic yolk sac
    to form anterior brain regions and a beating heart
  authors:
  - Gianluca Amadei
  - Charlotte E Handford
  - Joachim De Jonghe
  - Florian Hollfelder
  - David Glover
  - Magdalena Zernicka-Goetz
  publisher: Cold Spring Harbor Laboratory
  date: '2022-08-02'
  link: https://doi.org/gtnwbg
  orcid: 0000-0001-5405-968X
  plugin: orcid.py
  file: orcid.yaml
- id: doi:10.21203/rs.3.pex-2006/v1
  title: Stem cell-derived mouse embryos develop within an extra-embryonic yolk sac
    to form anterior brain regions and a beating heart-like structure.
  authors:
  - Gianluca Amadei
  - Charlotte E. Handford
  - David Glover
  - Magdalena Zernicka-Goetz
  publisher: Research Square Platform LLC
  date: '2022-08-26'
  link: https://doi.org/gtnwbh
  orcid: 0000-0001-5405-968X
  plugin: orcid.py
  file: orcid.yaml
- id: doi:10.6084/m9.figshare.21792463.v1
  title: Supp. Figure S1 from Behind the developing brains and beating hearts of stem
    cell-derived embryo models
  authors:
  - Gianluca Amadei
  - David M. Glover
  publisher: The Royal Society
  date: '2022-01-01'
  link: https://doi.org/gtnwbj
  orcid: 0000-0001-5405-968X
  plugin: orcid.py
  file: orcid.yaml
- id: doi:10.1016/j.devcel.2020.12.004
  title: "Inducible Stem-Cell-Derived Embryos Capture Mouse Morphogenetic Events In\_\
    Vitro"
  authors:
  - Gianluca Amadei
  - Kasey Y.C. Lau
  - Joachim De Jonghe
  - Carlos W. Gantner
  - Berna Sozen
  - Christopher Chan
  - Meng Zhu
  - Christos Kyprianou
  - Florian Hollfelder
  - Magdalena Zernicka-Goetz
  publisher: Developmental Cell
  date: '2021-02-01'
  link: https://doi.org/grprdq
  orcid: 0000-0001-5405-968X
  plugin: orcid.py
  file: orcid.yaml
- id: doi:10.1038/s41586-020-2264-2
  title: Basement membrane remodelling regulates mouse embryogenesis
  authors:
  - Christos Kyprianou
  - Neophytos Christodoulou
  - Russell S. Hamilton
  - Wallis Nahaboo
  - Diana Suarez Boomgaard
  - Gianluca Amadei
  - Isabelle Migeotte
  - Magdalena Zernicka-Goetz
  publisher: Nature
  date: '2020-05-06'
  link: https://doi.org/ghcx44
  orcid: 0000-0001-5405-968X
  plugin: orcid.py
  file: orcid.yaml
- id: doi:10.1038/s41556-018-0187-z
  title: 'Publisher Correction: Self-assembly of embryonic and two extra-embryonic
    stem cell types into gastrulating embryo-like structures'
  authors:
  - Berna Sozen
  - Gianluca Amadei
  - Andy Cox
  - Ran Wang
  - Ellen Na
  - Sylwia Czukiewska
  - Lia Chappell
  - Thierry Voet
  - Geert Michel
  - Naihe Jing
  - David M. Glover
  - Magdalena Zernicka-Goetz
  publisher: Nature Cell Biology
  date: '2018-08-08'
  link: https://doi.org/gdxxq3
  orcid: 0000-0001-5405-968X
  plugin: orcid.py
  file: orcid.yaml
- id: doi:10.1038/s41556-018-0147-7
  title: Self-assembly of embryonic and two extra-embryonic stem cell types into gastrulating
    embryo-like structures
  authors:
  - Berna Sozen
  - Gianluca Amadei
  - Andy Cox
  - Ran Wang
  - Ellen Na
  - Sylwia Czukiewska
  - Lia Chappell
  - Thierry Voet
  - Geert Michel
  - Naihe Jing
  - David M. Glover
  - Magdalena Zernicka-Goetz
  publisher: Nature Cell Biology
  date: '2018-07-23'
  link: https://doi.org/gd2d4f
  orcid: 0000-0001-5405-968X
  plugin: orcid.py
  file: orcid.yaml
- id: doi:10.1523/jneurosci.2172-15.2015
  title: A Smaug2-Based Translational Repression Complex Determines the Balance between
    Precursor Maintenance versus Differentiation during Mammalian Neurogenesis
  authors:
  - Gianluca Amadei
  - Mark A. Zander
  - Guang Yang
  - Jason G. Dumelie
  - John P. Vessey
  - Howard D. Lipshitz
  - Craig A. Smibert
  - David R. Kaplan
  - Freda D. Miller
  publisher: The Journal of Neuroscience
  date: '2015-11-25'
  link: https://doi.org/f728rk
  orcid: 0000-0001-5405-968X
  plugin: orcid.py
  file: orcid.yaml
- id: doi:10.1016/j.stem.2012.06.010
  title: An Asymmetrically Localized Staufen2-Dependent RNA Complex Regulates Maintenance
    of Mammalian Neural Stem Cells
  authors:
  - "John\_P. Vessey"
  - Gianluca Amadei
  - "Sarah\_E. Burns"
  - "Michael\_A. Kiebler"
  - "David\_R. Kaplan"
  - "Freda\_D. Miller"
  publisher: Cell Stem Cell
  date: '2012-10-01'
  link: https://doi.org/f3snsz
  orcid: 0000-0001-5405-968X
  plugin: orcid.py
  file: orcid.yaml
- id: doi:10.1002/rcm.5293
  title: "Quantification of character\u2010impacting compounds in <i>Ocimum basilicum</i>\
    \ and 'Pesto alla Genovese' with selected ion flow tube mass spectrometry"
  authors:
  - Gianluca Amadei
  - Brian M. Ross
  publisher: Rapid Communications in Mass Spectrometry
  date: '2011-12-22'
  link: https://doi.org/fx7wqn
  orcid: 0000-0001-5405-968X
  plugin: orcid.py
  file: orcid.yaml
- id: doi:10.1002/rcm.4845
  title: The reactions of a series of terpenoids with H<sub>3</sub>O<sup>+</sup>,
    NO<sup>+</sup> and O studied using selected ion flow tube mass spectrometry
  authors:
  - Gianluca Amadei
  - Brian M. Ross
  publisher: Rapid Communications in Mass Spectrometry
  date: '2010-12-14'
  link: https://doi.org/b4dtb7
  orcid: 0000-0001-5405-968X
  plugin: orcid.py
  file: orcid.yaml
- id: doi:10.1371/journal.pcbi.1007128
  title: Open collaborative writing with Manubot
  authors:
  - Daniel S. Himmelstein
  - Vincent Rubinetti
  - David R. Slochower
  - Dongbo Hu
  - Venkat S. Malladi
  - Casey S. Greene
  - Anthony Gitter
  publisher: PLOS Computational Biology
  date: '2020-12-04'
  link: https://doi.org/c7np
  type: paper
  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed
    do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
  - type: manubot
    link: https://greenelab.github.io/meta-review/
  - type: source
    text: Manuscript Source
    link: https://github.com/greenelab/meta-review
  - type: website
    link: http://manubot.org/
  tags:
  - open science
  - collaboration
  repo: greenelab/meta-review
  plugin: sources.py
  file: sources.yaml
- id: doi:10.1016/j.csbj.2020.05.017
  title: Constructing knowledge graphs and their biomedical applications
  authors:
  - David N. Nicholson
  - Casey S. Greene
  publisher: Computational and Structural Biotechnology Journal
  date: '2020-01-01'
  link: https://doi.org/gg7m48
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg
  plugin: sources.py
  file: sources.yaml
- id: doi:10.7554/eLife.32822
  title: Sci-Hub provides access to nearly all scholarly literature
  authors:
  - Daniel S Himmelstein
  - Ariel Rodriguez Romero
  - Jacob G Levernier
  - Thomas Anthony Munro
  - Stephen Reid McLaughlin
  - Bastian Greshake Tzovaras
  - Casey S Greene
  publisher: eLife
  date: '2018-03-01'
  link: https://doi.org/ckcj
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
  plugin: sources.py
  file: sources.yaml
